public class Apexsum {
    public static integer add(integer a, integer b)
    {
        integer ab = a+b ;
        system.debug(ab);
        return ab;
    }
    
    public static integer sub(integer a, integer b)
    {
        integer ab = a-b ;
        system.debug(ab);
        return ab;
    }
    
public static integer multi(integer a, integer b)
    {
        integer ab = a*b ;
        system.debug(ab);
        return ab;
    }
    public static integer div(integer a, integer b)
    {
        integer ab = a/b ;
        system.debug(ab);
        return ab;
    }

  }