public class firstprogram {
    public static void Test()
    {
        String Name ='welcome';
        system.debug(Name);
        Integer n =2717;
        system.debug('n');
        Boolean Res= true;
        system.debug('res');
        Decimal num = 56.22;
        system.debug(num);
        date CD =Date.newInstance(2000, 07, 27);
        system.debug(CD);
        id record ='0015j00000aqpE1AAI';
        system.debug(record);
        DateTime S = Datetime.newInstance(2000,09,17,12,00,00);
        system.debug(S);
    
}
}