public class Futureapex {
 public   futureapex()
    {
        system.debug('Constructor');
        school();
        books();
        lunch(); 
        exam();        
    }
    public void school()
    {
        system.debug('first step of our life :)');
    }
    public void books()
    {
        system.debug('Improve our knowledge :)');
    }
    public void lunch()
    {
        system.debug('Eat well : ');
    }
    @future
    public static void Exam()
        {
            system.debug('Do well');
        }
}